language: python
python:  
  - "2.7"  
# command to install dependencies
cache: pip
install: 
  - "pip install -r requirements.txt"
before_script:
  - mkdir RunningRoom
  - mkdir RunningRoom/data
script:
  - "pep8 ."
  - python tests.py --all